name: model-training
on:
  push:
    branches:
      - 'training/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull dataset.dvc
          python train_cnn.py

          cat "## Model results" >> report.md
          cml-publish loss.png --md >> report.md
          cml-publish val_accuracy.png --md >> report.md
          cml-send-comment report.md
